// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihwwdhbzyrwhxjzorkef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod3dkaGJ6eXJ3aHhqem9ya2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzE1MTgsImV4cCI6MjA2Mzc0NzUxOH0.9YGI-36aZIcGRJ38ea0yYmvyOWQ5Hki0WvglmNEJaBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);